# Initialization file for the KUKA Fast Research Interface of the Light-Weight Robot IV

[RobotName]
Name=472

[Priorities]
#Priority range: 1..99
KRCCommunicationThread=99
TimerThread=55
MainThread=50
OutputConsoleThread=5

[ControlValues]
# Cycle time in seconds
CycleTime=0.001

[Logging]
NumberOfLoggingFileEntries=60000
LoggingPath=/home/lwrcontrol/output
LoggingFileName=LWR-Scope.dat
